/**
 * Constants for "Verification" reasons in signed work order processing.
 * 
 * These reasons are used when a signed PDF cannot be automatically processed
 * and requires manual review.
 */

export const NEEDS_REVIEW_REASONS = {
  TEMPLATE_NOT_CONFIGURED: "TEMPLATE_NOT_CONFIGURED",
  TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",
  INVALID_CROP: "INVALID_CROP",
  CROP_TOO_SMALL: "CROP_TOO_SMALL",
  PAGE_MISMATCH: "PAGE_MISMATCH",
  TEMPLATE_PAGE_SIZE_MISMATCH: "TEMPLATE_PAGE_SIZE_MISMATCH",
  LOW_CONFIDENCE_AFTER_RETRY: "LOW_CONFIDENCE_AFTER_RETRY",
  INVALID_WORK_ORDER_NUMBER: "INVALID_WORK_ORDER_NUMBER",
  FMKEY_MISMATCH: "FMKEY_MISMATCH",
  NO_WORK_ORDER_NUMBER: "NO_WORK_ORDER_NUMBER",
  NO_MATCHING_JOB_ROW: "NO_MATCHING_JOB_ROW",
  UPDATE_FAILED: "UPDATE_FAILED",
  LOW_CONFIDENCE: "LOW_CONFIDENCE",
  QUICK_CHECK_RECOMMENDED: "QUICK_CHECK_RECOMMENDED",
  NEEDS_ATTENTION: "NEEDS_ATTENTION",
} as const;

export type NeedsReviewReason =
  (typeof NEEDS_REVIEW_REASONS)[keyof typeof NEEDS_REVIEW_REASONS];

